"""add guest_profiles, tasks, pomodoro_sessions

Revision ID: ff1506a3b6de
Revises:
Create Date: 2026-08-15 19:30:36.403824

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "ff1506a3b6de"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "guest_profiles",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "tasks",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("title", sa.String(length=255), nullable=False),
        sa.Column("estimated_pomodoros", sa.Integer(), nullable=False),
        sa.Column("completed_pomodoros", sa.Integer(), nullable=False),
        sa.Column("is_completed", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["guest_profiles.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("tasks", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_tasks_user_id"), ["user_id"], unique=False)

    op.create_table(
        "pomodoro_sessions",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("task_id", sa.Uuid(), nullable=True),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column(
            "session_type",
            sa.Enum(
                "WORK",
                "SHORT_BREAK",
                "LONG_BREAK",
                name="sessiontype",
                native_enum=False,
                length=20,
            ),
            nullable=False,
        ),
        sa.Column("duration_minutes", sa.Integer(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "COMPLETED",
                "INTERRUPTED",
                name="sessionstatus",
                native_enum=False,
                length=20,
            ),
            nullable=False,
        ),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("ended_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["task_id"], ["tasks.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["user_id"], ["guest_profiles.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("pomodoro_sessions", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_pomodoro_sessions_started_at"), ["started_at"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_pomodoro_sessions_task_id"), ["task_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_pomodoro_sessions_user_id"), ["user_id"], unique=False
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("pomodoro_sessions", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_pomodoro_sessions_user_id"))
        batch_op.drop_index(batch_op.f("ix_pomodoro_sessions_task_id"))
        batch_op.drop_index(batch_op.f("ix_pomodoro_sessions_started_at"))

    op.drop_table("pomodoro_sessions")
    with op.batch_alter_table("tasks", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_tasks_user_id"))

    op.drop_table("tasks")
    op.drop_table("guest_profiles")
    # ### end Alembic commands ###
